add_newline = true

[character]
error_symbol = "[✗](bold red) "

[directory]
truncation_length = 8
truncate_to_repo = true

[git_state]
style = "bold blue"

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
modified = "*"
untracked = "%"
up_to_date = "="

[username]
format = "[$user]($style)@"

#
# Modules I don't care about
#

[aws]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[cmd_duration]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[fill]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[rlang]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[terraform]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
