inherits = "papercolor-light"

"ui.selection.primary" = {bg="primary_selection_background", fg="primary_selection_foreground"}

[palette]
primary_selection_foreground="#eeeeee"
primary_selection_background="#0087af"
