inherits = "papercolor-light"

"ui.selection.primary" = {bg="primary_selection_background", fg="primary_selection_foreground"}
"ui.cursor.primary" = {bg="primary_cursor_background", fg="primary_cursor_foreground"}

[palette]
primary_cursor_foreground="#eeeeee"
primary_cursor_background="#ff0000"
primary_selection_foreground="#eeeeee"
primary_selection_background="#0087af"
