set nocompatible

filetype plugin indent on
syntax enable

set autoindent
set backspace=indent,eol,start
set cmdheight=2
set complete-=i
set display+=lastline
set expandtab
set history=200
set hlsearch
set incsearch
set laststatus=2
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+,eol:$
set modeline
set mouse=a
set nrformats-=octal
set number
set ruler
set scrolloff=3
set shiftwidth=4
set sidescrolloff=5
set smarttab
set softtabstop=4
set splitbelow
set splitright
set wildmenu

let mapleader = "\<Space>"
let maplocalleader = "\\"

nnoremap <silent> <C-L> :<C-U>nohlsearch<CR><C-L>
nnoremap <silent> <Leader>r :set relativenumber!<CR>
nnoremap <silent> <Leader>l :set list!<CR>
